 * Running on http://127.0.0.1:8802/
Traceback (most recent call last):
  File "app.py", line 50, in <module>
    app.run(port=8802, debug=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 706, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
 * Running on http://127.0.0.1:8802/
 * Restarting with reloader
127.0.0.1 - - [30/Jul/2014 15:59:52] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [30/Jul/2014 15:59:52] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2014 16:00:10] "POST /search HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2014 16:00:13] "GET /recrawl?search=pendrive HTTP/1.1" 302 -
127.0.0.1 - - [30/Jul/2014 16:00:13] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2014 16:00:49] "POST /search HTTP/1.1" 200 -
